### ISSUE TITLE
timeout waiting for response - RESOLVED using RespTimeout parameter

### ISSUE THREAD

**Issue by tahseenjamal** [fiorix/go-smpp#106]
Is this go-smpp issue or issue at the SMPP Server ? 

Any message submitted to SMPP throws back "timeout waiting for response"

**Comment by Munmendu** [comment]
This issue i also observed. As per the code,callback should hit for SMPP_SM_RESP but it never hit,although all SUBMIT_SM are sent from application.

Can anyone help us for the same.

**Comment by Munmendu** [comment]
Solution is there. We had fixed it.After internal review we will update.

**Comment by tahseenjamal** [comment]
so when is it getting updated so that I update fetch again ?

**Comment by tahseenjamal** [comment]
@Munmendu any update when would it be pushed as update ?

**Comment by tahseenjamal** [comment]
> Solution is there. We had fixed it.After internal review we will update.

Dear @Munmendu can you please provide the solution as beta solution. As this is a serious issue

**Comment by tahseenjamal** [comment]
@Munmendu Can we get resolution for this please ?

**Comment by tahseenjamal** [comment]
@fiorix 
Is this 'timeout waiting for response' resolved ?

**Comment by fiorix** [comment]
I think this is a question to @Munmendu who claims to have a solution. I have not had visibility into the problem or solution and haven't actively used this code in over 5 years now ;)

**Comment by tahseenjamal** [comment]
@fiorix I doubt @Munmendu has solution else he would have mentioned

**Comment by tahseenjamal** [comment]
@fiorix 
I figured it out. In transceiver we have to set value for RespTimeout parameter

RespTimeout : 10 * time.Second


and the issue stopped completely
