### ISSUE TITLE
TLVBody.SerializeTo doesn't write to io.writer

### ISSUE THREAD

**Issue by haisum** [fiorix/go-smpp#12]
Line 30 on `pdufield/tlvbody.go`, SerializeTo function doesn't write anything to io.Writer.

**Comment by haisum** [comment]
Pull request: https://github.com/fiorix/go-smpp/pull/13

**Comment by fiorix** [comment]
Not surprised, I never really tested TLV. There's probably TODOs in the code, which is mostly inherited from Kevin's lib.
