### ISSUE TITLE
short_message in DeliverSM scrambles when data_coding is 0x08 

### ISSUE THREAD

**Issue by haisum** [fiorix/go-smpp#14]
When receiving DeliverSM of a UCS encoded message, short_message gets decoded using UCS2 and gets corrupt. A solution is, not to decode short_message when decoding PDU and let user decide what to do.

Current output of short_message pdu field:
![selection_078](https://cloud.githubusercontent.com/assets/911409/14583775/d4bcd2ec-0445-11e6-9d77-5b43339133d3.png)

After I removed automatic decoding:
![selection_079](https://cloud.githubusercontent.com/assets/911409/14583777/e298c56a-0445-11e6-8866-7ccdebe89a25.png)

**Comment by haisum** [comment]
See pull request https://github.com/fiorix/go-smpp/pull/15 . I am not sure if it's correct fix. Input is welcome.

**Comment by fiorix** [comment]
Maybe the problem with the decoding is something else? Looks like buffer garbage to me.

**Comment by fiorix** [comment]
Mmmm, not really. I see it now. Not sure what to do either, decoding just the "Text: ..." part doesn't seem right, but on the other hand decoding it manually, later, can lead to a lot of repetitive code.

**Comment by haisum** [comment]
Until we come up with better solution to handle this, I think default decoding should be disabled because it will break whole short_message instead of just the part after Text:

**Comment by fiorix** [comment]
Sure, go ahead.

**Comment by fiorix** [comment]
Implemented in 5fe065f885a3e7b8f250f142d1c5b1eec80f9a5d. Thanks again!
