### ISSUE TITLE
Q: When using transceiver.Submit(), does the handler get the SubmitSMResp as well?

### ISSUE THREAD

**Issue by cesar0094** [fiorix/go-smpp#29]
I am using the transceiver to submit a SM, and receiving the response back successfully, but I also have a handler that wants to process the SubmitSMResp. Right now, it seems that it doesn't get passed to the handler, am I correct?

**Comment by fiorix** [comment]
Submit is a full blocking transaction that handles the response automatically. It won't trigger SubmitSMResp.
