### ISSUE TITLE
Crash when disconnect happens while submitting message

### ISSUE THREAD

**Issue by VDVsx** [fiorix/go-smpp#32]
When submitting a message and connection drops middle sending a crash can happen since  response PDU is empty here: https://github.com/fiorix/go-smpp/blob/master/smpp/transmitter.go#L294
At this point "resp" var contains: &{<nil> not connected}, so I could fix this just by checking for nil and return the error inside the resp var if it exists, if you think it should be fixed somewhere else please let me know.

**Comment by fiorix** [comment]
Definitely, please send a patch.
