### ISSUE TITLE
Method for sending additional fields with SMS

### ISSUE THREAD

**Issue by haisum** [fiorix/go-smpp#4]
Firstly, thanks for really awesome work. I have used and tested this package for simple sms and it works on smppsim simulator. My real smpp provided wants `addrton`,`dest_addr_ton`, `source_addr_npi` and `addr_npi` to be provided. If I send sms without these fields using Submit method it says invalid source address.

Method `func (t *Transmitter) Submit(sm *ShortMessage) (*ShortMessage, error)` doesn't support a parmeter to send additional fields along with simple ones. May I suggest a new method with signature:

`func (t *Transmitter) SubmitWithFields(sm *ShortMessage, fields map[string]interface{}) (*ShortMessage, error)`

I tried implementing above using following code:

```go

// SubmitWithFields sends a short message along with extra pdu fields and returns and updates the given
// sm with the response status. It returns the same sm object.
func (t *Transmitter) SubmitWithFields(sm *ShortMessage, fields map[string]int) (*ShortMessage, error) {
	p := pdu.NewSubmitSM()
	f := p.Fields()
	f.Set(pdufield.SourceAddr, sm.Src)
	f.Set(pdufield.DestinationAddr, sm.Dst)
	f.Set(pdufield.ShortMessage, sm.Text)
	f.Set(pdufield.RegisteredDelivery, uint8(sm.Register))
	for k, v := range fields {
		err := f.Set(pdufield.Name(k), v)
		if err != nil {
			return sm, fmt.Errorf("Couldn't set field %s with value %s. Error: %s", k, v, err)
		}
	}
	// Check if the message has validity set.
	if sm.Validity != time.Duration(0) {
		f.Set(pdufield.ValidityPeriod, convertValidity(sm.Validity))
	}
	resp, err := t.do(p)
	if err != nil {
		return nil, err
	}
	sm.resp.Lock()
	sm.resp.p = resp.PDU
	sm.resp.Unlock()
	if id := resp.PDU.Header().ID; id != pdu.SubmitSMRespID {
		return sm, fmt.Errorf("unexpected PDU ID: %s", id)
	}
	if s := resp.PDU.Header().Status; s != 0 {
		return sm, s
	}
	return sm, resp.Err
}
```

but when I submit with this method, smppsim disconnects and times out. Is there any better way via which I can send additional fields?

**Comment by fiorix** [comment]
I'd rather extend the `ShortMessage` struct to support additional fields instead of creating another method for the `Transmitter`. This should be an easy fix, see `transmitter.go` for more.

I can work on this next week when I'm back home. Currently traveling with limited internet access and time.

**Comment by fiorix** [comment]
Could you please share sample values you're using for your tests, for the extra PDUs?

**Comment by haisum** [comment]
Thanks for replying fast. Have a question if I am not bothering you on your trip:

Why is calling ```f.Set(pdufield.Name(k), v)``` causing packet to become malformed and showing exception in smppsim. Same method is being called for `SourceAddr` and `DestinationAddr` but as soon as I do `f.Set(pdufield.Name("addr_ton"), 1)` smppsim starts complaining and sends error: "timeout waiting for response" before disconnecting.

**Comment by fiorix** [comment]
Ok, give it a try now and let me know if you have any troubles. I can reopen in case of problems, but according to the tests I've done it should work just fine now.

**Comment by haisum** [comment]
I love you man :D #nohomo

**Comment by fiorix** [comment]
lol :)
