### ISSUE TITLE
Support 2 byte reference number in UDH header

### ISSUE THREAD

**Issue by lucianjon** [fiorix/go-smpp#45]
Hey there, 

We're going to be running some services with this library that are going to be using a fairly large number of binds. With the current 1 byte reference number the chance of a collision would be relatively high and we'd like to use the alternative header with the 2 byte number. For now we've patched the library to add it in but was wanting to ask if you would accept a PR for it?

Cheers,
Lucian

**Comment by fiorix** [comment]
That's cool. I'd be happy to review.

**Comment by lucianjon** [comment]
Alright I'll get started on it when I have a chance. Would you be alright with just supporting the 2 byte header or would you like to keep support for both?

**Comment by fiorix** [comment]
If it doesn't break anything else it'd be fine with just 2, otherwise we need both.

**Comment by lucianjon** [comment]
Alright I've created the PR, as far as I'm aware both are fully supported in SMPP 3.4 but if you'd prefer I could create another function to use the longer header

**Comment by fiorix** [comment]
Currently I don't have access to anything other than a simulator, so can't really tell whether SMSCs will play nice with this.

**Comment by lucianjon** [comment]
We've tested it with the simulator and the SMPP provider we use and both have worked. It's hard to track down whether it's a part of the base SMPP 3.4 spec though.

**Comment by fiorix** [comment]
Thanks! 👍
