### ISSUE TITLE
Support messages larger than characters allowed per sms

### ISSUE THREAD

**Issue by haisum** [fiorix/go-smpp#5]
I tried sending larger than one sms content UCS (60+) and Latin(160+) encoded data using ShortMessage struct but it failed on smpp service provided by cellular network. Sending large latin encoded messages work on smppsim. Smppsim fails to process any ucs encoded messages. I read up on it and came across these at http://www.activexperts.com/sms-component/smpp-specifications/smpp-parameter-definition/ :

**short_message**

The short_message parameter contains the user data. A maximum of 254 octets can be sent. ESME's should use the optional message_payload parameter in submit_sm, submit_multi, and deliver_sm to send *larger user data sizes*.

**sm_length**

The sm_length parameter specifies the length of the short_message parameter in octets. The sm_length *should be set to 0 in the submit_sm, submit_multi, and deliver_sm PDUs if the message_payload parameter is being used to send user data larger than 254 octets*.

If above is right, can this library support sending larger than 160 chars messages? I couldn't find any logic to handle this in code.

**Comment by fiorix** [comment]
It's definitely possible. As of now, whenever we set the `ShortMessage` `PDU` we also set `SMLength` to the message length.

This is the code to handle the case above:

https://github.com/fiorix/go-smpp/blob/master/smpp/pdu/pdufield/map.go#L46

**Comment by haisum** [comment]
Code uses **short_message** field instead of **message_payload** and sets SMLength for message regardless of its size. If above documentation and my understanding is right, any message above 160 latin chars should be using message_payload and 0 for SMLength.

**Comment by haisum** [comment]
I get this when sending UCS encoded data longer than 60 chars:

0x000000c0: "error in the optional part of the pdu body",

**Comment by haisum** [comment]
Any input on this? Is there a workaround?

**Comment by fiorix** [comment]
Want to take a crack at it and send a PR? I'd be happy to review.
Otherwise I might come back and do this whenever I find the time. I think it should be a simple change in the file linked above.

**Comment by haisum** [comment]
@fiorix sorry for not giving a PR. I did change code on my end and tried with message_payload. Apparently many smpp providers don't support it even though it's part of protocol. More reliable way of sending multiple messages is by setting UDH header as defined at https://en.wikipedia.org/wiki/Concatenated_SMS#Sending_a_concatenated_SMS_using_a_User_Data_Header 

Also check https://help.nexmo.com/hc/en-us/articles/204015653-Sending-Concatenated-Messages

and there's a java example here https://itprobes.wordpress.com/2009/09/05/hello-world/ 

How do we send this UDH header via this library?

**Comment by fiorix** [comment]
What I understand from the first answer on this link http://stackoverflow.com/questions/16351463/can-anybody-tell-me-how-to-use-user-data-in-smpp it means we have to set the `ShortMessage` PDU field of the `SubmitSM` command to the UDH binary blob, and set the `ESMClass` PDU to 0x40.

What we could do is have a `LongMessage` boolean field in the `ShortMessage` struct to indicate that the message should be encoded with UDH. The link you posted from nexmo has a good example of what it looks like.

**Comment by AlekSi** [comment]
:+1:

**Comment by haisum** [comment]
@fiorix yes you're right. We don't even need LongMessage field, we can check encoding and then if it's UCS-2 and larger than 70 chars it should be split, if it's latin and larger than 160 chars it should be split and ShortMessage should have UDH set along with ESMClass.

**Comment by xintron** [comment]
My recommendation would be to do something similar to what @haisum linked to (the PHP library). Have a helper method that generates a slice of Submits that automatically takes care of the splitting of the message and prepending of UDH. This way the Submit struct is kept clean.

The method could then itself send the Submits or just return the slice and let the user decide how/when to send them.

**Comment by fiorix** [comment]
Yeah this is definitely a better option!

**Comment by AlekSi** [comment]
We have quick and dirty working implementation here: https://github.com/zaikin/go-smpp/commit/62a69dc1720710e76d74a1e86a7d880201e9e0e7

**Comment by fiorix** [comment]
I like the fact that it is automatic in this particular case.

Can you split the two cases in functions, remove log.Print and submit a patch? I've added a couple comments there.

**Comment by AlekSi** [comment]
@zaikin May you do it please?

**Comment by AlekSi** [comment]
See #7

**Comment by AlekSi** [comment]
#7 is merged. If anyone want to test it or propose a different approach or do a refactoring, it's better to do is sooner than later, especially if you want to break API.

**Comment by fiorix** [comment]
If we do the refactor I mentioned in #7 it shouldn't break. Objections?
