### ISSUE TITLE
How to check if transmitter is bound ?

### ISSUE THREAD

**Issue by Zensey** [fiorix/go-smpp#54]
I want to restrict Send() of message during reconnects.
If Bind_tranciever coincide with Submit_sm it causes Bind to fail  -- SMSC does not answer on Bind.

**Comment by Zensey** [comment]
Oh, I have found the way:

```   conn_st_ch := c.tx.Bind()
    go func() {
        for {
            select {
            case conn_st := <-conn_st_ch:
                c.bound = conn_st.Status() == smpp.Connected
                log.Println("bound>", c.bound, c.id)
            }
        }
    }()
```

**Comment by fiorix** [comment]
Cool :)

Let me know if you still need any help and I'm happy to reopen this.
