### ISSUE TITLE
Datacoding type for Wappush

### ISSUE THREAD

**Issue by evxzibit** [fiorix/go-smpp#55]
First of all, Thank you for this awesome plugin.
Is it possible to send WapPush message if this plugin?
I read that you need to set the datacoding to 245 but from the 3 available datacoding types on this plugin i am not sure which one it is if it is any of these at all or is there a way i can set up the **Text** parameter of the message to switch my need?

Thank you

**Comment by fiorix** [comment]
You're right, we don't support that specific data coding. Yes, you can implement your own text codec by implementing the https://godoc.org/github.com/fiorix/go-smpp/smpp/pdu/pdutext#Codec interface.

Once you have your codec ready you can pass it in the https://godoc.org/github.com/fiorix/go-smpp/smpp#ShortMessage's Text field.
