### ISSUE TITLE
Arabic sms looks fuzzy

### ISSUE THREAD

**Issue by hamdongunner** [fiorix/go-smpp#60]
whenever I send an SMS in **Arabic** it looks weird

"هلو" => "YìYèYò"

**Comment by nezorflame** [comment]
Check encoding, you should use Unicode for this.

**Comment by hamdongunner** [comment]
@nezorflame 
I just replace 
`Text:     pdutext.ROW(r.FormValue("text")),`
with 
`Text:     pdutext.UCS2(r.FormValue("text")),`

and everything is good now Thank you
