### ISSUE TITLE
ошибка подключения SMPP

### ISSUE THREAD

**Issue by SKletsov** [fiorix/go-smpp#63]
Можете подсказать делаю пакет для API своего https://play.golang.org/p/ES7Fv1tuzJz . Но ошибка идетъ
err con
2018/02/06 17:49:59 SMPP connection status: Connected
err con
2018/02/06 17:50:33 SMPP connection status: Connected
err con
2018/02/06 17:51:22 SMPP connection status: Connected

в связи с чем такая ошибка может возникать

**Comment by nezorflame** [comment]
###Translation

Can you please help?
I'm making my solution for the API (example at https://play.golang.org/p/ES7Fv1tuzJz).
Log shows this:

```
err con
2018/02/06 17:49:59 SMPP connection status: Connected
err con
2018/02/06 17:50:33 SMPP connection status: Connected
err con
2018/02/06 17:51:22 SMPP connection status: Connected
```

Need help regarding this.

**Comment by nezorflame** [comment]
Check initial connection error before creating goroutine:

```go
func main() {
	// make persistent connection
	var status smpp.ConnStatus

	tx := &smpp.Transmitter{
		Addr:   "xxxxxxx:4000",
		User:   "5",
		Passwd: "dctlkznfrcb",
	}
	conn := tx.Bind()
	if status = <-conn; status.Error() != nil {
		fmt.Println("Unable to connect, aborting: ", status.Error())
		return
	}
	fmt.Println("Connection completed, status:", status.Status().String())

	// launch connection checker goroutine
	go func() {
		for c := range conn {
			log.Println("SMPP connection status:", c.Status())
		}
	}()

	// send SMS
	sendSMS(tx, "1", "2", "3")
}
```

**Comment by nezorflame** [comment]
@fiorix I think we should advise this flow for the example usage, so that people don't forget to check the first incoming ConnStatus.

**Comment by fiorix** [comment]
@nezorflame absolutely, this needs better documentation. I believe a simple comment in the example code would do already - assuming that people actually read it :D
