### ISSUE TITLE
is it possible receive USSD and response?

### ISSUE THREAD

**Issue by Abdukahhor** [fiorix/go-smpp#67]
Example 
I am calling &ast;933&ast;Hello#, mobile operator sends to endpoint.
Endpoint responses "Hi there" to mobile operator and I receive "Hi There"
is possible to do USSD with go-smpp?

**Comment by fiorix** [comment]
afaik USSD is just a flag in the message for the transmitter... and if the smsc sends a response back it should land in your receiver
