### ISSUE TITLE
Submitting custom PDU from Transmitter

### ISSUE THREAD

**Issue by Alexey1100** [fiorix/go-smpp#68]
I'm wondering is there a way to submit a custom PDU from Transmitter, not using predefined Submit and SubmitLongMsg methods?

E.g getting DELIVER_SM pdu, changing header ID to SUBMIT_SM and pushing it back to SMSC.

**Comment by fiorix** [comment]
Not day. You'd have to implement your own method in the transmitter that builds the PDU body and calls `do`: https://github.com/fiorix/go-smpp/blob/master/smpp/transmitter.go#L273

The problem with allowing people to do that is that responses would get back into the async response handler pipeline and if not handled correctly it could break the connection. This is why `do` is only available to the Transmitter itself.
