### ISSUE TITLE
Long message multi-part tracking

### ISSUE THREAD

**Issue by McSwitch** [fiorix/go-smpp#74]
Hi all,

Noticed that the library, when sending long messages, only returns the data for the last part of the multi-part message. This is due to the function only returning a single ShortMessage in the response:

`func (t *Transmitter) SubmitLongMsg(sm *ShortMessage) (*ShortMessage, error) {`

I would like to extend this function to return all parts of the multi-part message:

`func (t *Transmitter) SubmitLongMsg(sm *ShortMessage) ([]ShortMessage, error) {`

We could then keep track of the delivery status (via Delivery-Receipts) of each part of the multi-part message.

**Comment by fiorix** [comment]
Dup of #72 

If there is a solution I'm happy to reopen both issues.
