### ISSUE TITLE
Problems using test server

### ISSUE THREAD

**Issue by cesar0094** [fiorix/go-smpp#9]
Hi,

I am trying to use (and expand) the server in smpptest. I ran a server and took the sample code for running a client. When I try to submit a ShortMessage with `transmitter.Submit()`, I get the error `unexpected PDU ID: SubmitSM` which makes sense since the server is only responding back with the same PDU in the `EchoHandler`. 

In the `EchoHandler`, I modified the ID of the PDU to be `SubmitSMRespID` by accessing the headers of the request PDU and when I send it back, the client times out. I pinpointed the problem to be in `list.go:112` where it complains: `not enough data for tag 0x0: want 29554, have 22`.

I would imagine that messing directly with the headers could be a bad idea, so I went ahead and used the function `NewSubmitSMResp()` from `types.go` to build a the appropriate response in the `EchoHandler`. When I sent it back, the client just times out again with no response and I can't pinpoint the cause.

EchoHandler looks like this:
```
func EchoHandler(conn Conn, m pdu.Body) {
	// Approach #1: Send it back as-is

	// Approach #2: Modify the ID directly
	// m.Header().ID = pdu.SubmitSMRespID

	// Approach #3: Send a new response
	// m = pdu.NewSubmitSMResp()
	
	err := conn.Write(m)
	if err != nil {
		fmt.Println(err)
	}
}
```
What am I doing wrong? Or am I missing to implement something? I am quite knew to SMPP so bare with me if there are obvious mistakes I didn't spot.

Thanks!

**Comment by fiorix** [comment]
I think you have to start from creating a `pdu.NewSubmitSMResp()`, then populate the PDUs for the response correctly. You can run a simulator and see what it replies with when you Submit to it.

**Comment by cesar0094** [comment]
Thanks! I will try that.

**Comment by cesar0094** [comment]
I went ahead and used Selenium SMPPSim to see what was the difference between the replies I was sending back. I realized that I was not setting the `message_id` in `pdu.Fields()`, so I did that, but still it did not work. I noticed that the headers were also different from Selenium SMPPSim to the test server. The headers in the test server are not built appropriately, sending `Len=0`. I ran the tests in `server_test.go` and indeed this is the problem:

```
--- FAIL: TestServer (0.00s)
	server_test.go:63: unexpected header: want pdu.Header{Len:0x36, ID:0x4, Status:0x0, Seq:0x3}, have pdu.Header{Len:0x12, ID:0x80000004, Status:0x0, Seq:0x4}
```

I've tried comparing `Conn` in `smpp` and `smpptest` but there are no meaningful differences and they both handle the same object PDU so I am not sure where to look to solve this bug. Any suggestions?

Thanks again.

**Comment by cesar0094** [comment]
Tests are also not passing in `receiver_test.go`; they make use of server:

```
--- FAIL: TestReceiver (0.00s)
	receiver_test.go:43: unexpected PDU: want pdu.Header{Len:0x10, ID:0x80000000, Status:0x0, Seq:0x5}, have pdu.Header{Len:0x12, ID:0x80000004, Status:0x0, Seq:0x6}
```

**Comment by fiorix** [comment]
I put together a very rudimentary test based on `smpptest/server_test.go` that basically replaces the `EchoHandler` with my own `SubmitSMHandler`. It works just fine, not sure what your problem it.

http://play.golang.org/p/0FnEWGecUt

**Comment by cesar0094** [comment]
I was missing setting `header.Seq`, it now works. Thanks a lot!

**Comment by fiorix** [comment]
Yeah, the sequence number is what clients and servers use to keep track of requests and responses.
